export { default as Home } from './Home.vue';
export { default as Layout } from './Layout.vue';
export { default as Login } from './Login.vue';
export { default as Register } from './Register.vue';
export { default as Activities } from "./Activities.vue";
export { default as Perfil } from "./Perfil.vue";
export { default as AdminUsers } from "./AdminUsers.vue";
export { default as EditProfile } from "./EditProfile.vue";
export { default as Layout } from "./Layout.vue";
export { default as List } from "./List.vue";
export { default as Questions} from "./Questions.vue";
export { default as Ocorrencias} from "./Ocorrencias.vue";
